{% set name = "ablang" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ablang-{{ version }}.tar.gz
  sha256: 17a9a13827c14189cb0d86c97ed18af53608b46d78a6d310dae3b5f46eb3c6d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numba
    - numpy
    - python >={{ python_min }}
    - requests
    - pytorch >=1.6
    - pandas

test:
  requires:
    - python {{ python_min }}
  imports:
    - ablang

about:
  home: https://pypi.org/project/ablang/
  summary: 'AbLang: A language model for antibodies.'
  license: BSD-3-Clause
  license_file:
    - LICENSE
  dev_url: https://github.com/TobiasHeOl/AbLang

extra:
  recipe-maintainers:
    - jdblischak
    - sdvillal
